### ISSUE TITLE
Cutting files when zip.

### ISSUE THREAD

**Issue by yauheni-p** [aspose-zip/Aspose.ZIP-for-.NET#1]
Hello.
I try to zip 2 files:
![image](https://user-images.githubusercontent.com/45207703/61993765-65628e80-b079-11e9-96b3-0538c44db8aa.png)
My code:
![image](https://user-images.githubusercontent.com/45207703/61993770-7d3a1280-b079-11e9-8e96-839722f0722a.png)
Result:
![image](https://user-images.githubusercontent.com/45207703/61993783-b70b1900-b079-11e9-97cf-8c3b8559558a.png)
If file size more then 5 013 504 bytes it cuts to this size and corrupts. I have tried with other files and result was same.
How can i fix it?
Best regards

**Comment by Eugene85** [comment]
@yauheni-p this happens because of [limitation of trial version](https://docs.aspose.com/zip/net/licensing/#evaluation-version-limitations).
