### ISSUE TITLE
RAR File names are encrypted, how to deal with it?

### ISSUE THREAD

**Issue by ITBBOOK** [aspose-zip/Aspose.ZIP-for-.NET#10]
RAR File names are encrypted, how to deal with it? look there are always catch exception even I set correct password

  using (var a = new RarArchive(zipfile, new RarArchiveLoadOptions() { DecryptionPassword = password }))

  {
      a.ExtractToDirectory(zipFilePath);
      
  }

**Comment by Eugene85** [comment]
Hello @ITBBOOK, which version of Aspose.ZIP do you use? Please provide the sample RAR archive that fails to extract for us to review.

**Comment by ITBBOOK** [comment]
sorry my mistake. It works
