### ISSUE TITLE
RAR file when I try differnt password, there are always differnt exception captured even I try correct password.

### ISSUE THREAD

**Issue by ITBBOOK** [aspose-zip/Aspose.ZIP-for-.NET#11]
please find the rar file,  https://we.tl/t-0aPlUoa2Lr

the correct password is 'www.eshuyuan.com' , context between ' ', 
different exceptions occur when I try different password even I try correct password.
below is the code I used.

    using (RarArchive a = new RarArchive(rarFile, new RarArchiveLoadOptions() { DecryptionPassword = password }))
    {
         a.ExtractToDirectory(zipFilePath); 
    }

The excetions happens on  a.ExtractToDirectory(zipFilePath) when I try different password: 

Below is the exceptions happened:
 System.IndexOutOfRangeException, 
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')System.ArgumentOutOfRangeException
System.NullReferenceException:“Object reference not set to an instance of an object.”

Acutally I tried to upack it by WinRAR, it is totally no problem. Please help to check it. thanks a lot!

**Comment by Eugene85** [comment]
Hello, we have successfully extracted your archive with proper password. What version of Aspose.ZIP library are you using?

**Comment by ITBBOOK** [comment]
Aspose.ZIP 23.11.0.  I test it again, it works today. it's bit crazy. anyway, thanks a lot!
