### ISSUE TITLE
Archive the unzip has error file size...

### ISSUE THREAD

**Issue by acer1204** [aspose-zip/Aspose.ZIP-for-.NET#9]
this is my code.
`
 using (Archive archive = new Archive(fileName))
 {
     archive.ExtractToDirectory("zipbuffer\\AA");
 }
`
when i unzip this zip by internal zip, the dds file size is 8193kb
but if i use aspose.zip to unzip the same zip, the dds file size is 4883kb, and the file has problem to use.
it a bug?

**Comment by Eugene85** [comment]
Probably this happens because of [trial restrictions](https://docs.aspose.com/zip/net/licensing/#evaluate-asposezip).
